### ISSUE TITLE
Make doIt function public

### ISSUE THREAD

**Issue by Anubarak** [mmikkel/CpFieldInspect-Craft#11]
I found a strange issue or at least a very edge case scenario in your plugin.
When there is an internal call in Craft  for

```PHP
Craft::$app->getFields()->getAllFields();
```

and there are no fields yet, it will fetch all of them from the DB and loop those results to populate fields.
So it will call

```php
public function createField($config): FieldInterface
```
and it does

```php
$field = ComponentHelper::createComponent($config, FieldInterface::class);
```

 That function tries to validate it
```php
static::validateComponentClass($class, $instanceOf, true);
```

Remeber `$this->fields` is still `[]` because no field is created yet ¯\_(ツ)_/¯
Unfortunately if it comes really from a plugin, Craft will do the following
```php
// If it comes from a plugin, make sure the plugin is installed
$pluginsService = Craft::$app->getPlugins();
$pluginHandle = $pluginsService->getPluginHandleByClass($class);
if ($pluginHandle !== null && !$pluginsService->isPluginEnabled($pluginHandle)) {
```

```php
    /**
     * Returns whether a given plugin is installed and enabled.
     *
     * @param string $handle The plugin handle
     * @return bool
     */
    public function isPluginEnabled(string $handle): bool
    {
        $this->loadPlugins();
        return isset($this->_enabledPluginInfo[$handle]);
    }
```
The function `$this->loadPlugins();` is the key point here.... because it does what the name let's you think.. it loads all plugins and trigger the event

```php
if ($this->hasEventHandlers(self::EVENT_AFTER_LOAD_PLUGINS)) {
    $this->trigger(self::EVENT_AFTER_LOAD_PLUGINS);
}
```

Remeber when I told `$this->fields` is still an empty array? That's even now the case when your event is triggert
```php
// Handler: EVENT_AFTER_LOAD_PLUGINS
Event::on(
    Plugins::class,
    Plugins::EVENT_AFTER_LOAD_PLUGINS,
    function () {
        $this->doIt();
    }
);
```
So `$fields = Craft::$app->getFields()->getAllFields();` returns an empty array and no field will be marked with a wheel.
Currently my work-around is to copy your code in my custom module and run it again, but it would be easier to call the function `doIt` twice

**Comment by mmikkel** [comment]
I don't believe this is relevant anymore since I moved the `Craft::$app->getUser()->getIsAdmin()` query into a `EVENT_AFTER_LOAD_PLUGINS` handler w/ CP Field Inspect 1.0.7. Closing.
