### ISSUE TITLE
Hide cog wheels when allowAdminChanges is set to false

### ISSUE THREAD

**Issue by frontedbe** [mmikkel/CpFieldInspect-Craft#13]
Settings aren't available when allowAdminChanges is set to false so in that case there's no point in showing the cog wheel. Thanks!

**Comment by mmikkel** [comment]
Hi @mdominguez, thanks for the suggestion!

I'm torn. Sure, it doesn't make a ton of sense to have a link to a field's settings in environments where `allowAdminChanges` is `false`. On the other hand, it doesn't _hurt any_, and I think it's nice to have the field _handle_ available, regardless of that config setting?

Also, it's already possible to do what you want, by deactivating the plugin completely on a per-environment basis using the [`disabledPlugins`](https://docs.craftcms.com/v3/config/config-settings.html#disabledplugins) config setting in `config/general.php`:

```php
return [
    '*' => [
        ...
    ],
    'prod' => [
        'allowAdminChanges' => false,
        'disabledPlugins' => ['cp-field-inspect'],
    ],
];
```

**Comment by frontedbe** [comment]
Hi @mmikkel,

Indeed you're right! It was just when I noticed that a colleague of mine (not a dev) was trying to access the field settings to adjust something herself, which wasn't possible of course :) so thought this might be a good idea to hide the cog wheel altogether.

Thanks for the clarification!
