### ISSUE TITLE
"Edit Global Set" cog positioning is off with 3.4.x alpha

### ISSUE THREAD

**Issue by JayBox325** [mmikkel/CpFieldInspect-Craft#15]
See the blue cog in the screen below:

<img width="1432" alt="Screenshot 2019-11-21 at 12 27 25" src="https://user-images.githubusercontent.com/13233809/69338258-ab5fe580-0c5a-11ea-8317-7cdec474b024.png">

Craft version: 3.4.0-alpha-1
Browser: Firefox 70.0.1 on Mac

**Comment by mmikkel** [comment]
Hi @JayBox325, thanks for reporting and sorry for the late reply.

I'm working on a new version of CP Field Inspect which addresses this issue – should be out soon-ish.

**Comment by mmikkel** [comment]
Hi @JayBox325, this should be resolved in [CP Field Inspect v. 1.1.0.1](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.1.0.1). Here's how the "Edit Global Set" source link looks on 3.4.2+:

![image](https://user-images.githubusercontent.com/298510/74105092-239fbe00-4b5b-11ea-8220-46f0d12ac373.png)
