### ISSUE TITLE
Multiple cogs appearing on entries

### ISSUE THREAD

**Issue by fbnntt** [mmikkel/CpFieldInspect-Craft#16]
### Description
Came across a wee bug this morning. 
When selecting an asset/entry/etc in a field an extra cog appears each time the asset popup window appears then saved.

### Steps to reproduce

1. Go into an entry
2. Upload/pick an asset + save.
3. Another cog will appear

### Additional info

- Craft version: 3.4.6.1
- PHP version: 7.1
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

-------

![Screen Shot 2020-02-20 at 09 40 01](https://user-images.githubusercontent.com/13600951/74922142-b5fb5980-53c6-11ea-95c2-2e1a1b8bf114.png)

**Comment by mmikkel** [comment]
Thanks for reporting @fbnntt – gonna get that sorted ASAP.

**Comment by cakleimeier** [comment]
I'm facing the same issue: any time you click into an Entries or Assets field, another cog gets added.

**Comment by mmikkel** [comment]
Just published [CP Field Inspect 1.1.3](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.1.3), which should resolve this issue.
