### ISSUE TITLE
Cannot open field settings in new tab anymore

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/CpFieldInspect-Craft#17]
With latest update, we lost ability to open link to field settings in a new tab by clicking it with middle mouse button. 
Could this be restored?

**Comment by mmikkel** [comment]
Yeah... that's an oversight on my part, thanks for reporting. The links are now dependant on JS to fire the click event (only way I could get it to work inside the new field handle element), which is why that doesn't work out of the box. I'll look into adding support for that ASAP.

**Comment by mmikkel** [comment]
Resolved in [CP Field Inspect v. 1.2.2](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.2.2)

**Comment by piotrpog** [comment]
@mmikkel 
Is it really resolved? I still cannot use middle mouse button on gear icon.

**Comment by mmikkel** [comment]
@piotrpog Just tested it, and no – it appears not. Thanks for letting me know, I'll look into getting that fixed.

**Comment by mmikkel** [comment]
Should be fixed in [CP Field Inspect 1.2.5](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.2.5).
