### ISSUE TITLE
Cogwheel link to sub field settings in Neo fields link to the parent Neo field

### ISSUE THREAD

**Issue by lhs-dev** [mmikkel/CpFieldInspect-Craft#18]
When using Neo fields as content builders, the cogwheel links of the content block fields incorrectly points to the settings of the parent Neo field.

![image](https://user-images.githubusercontent.com/50990957/90621103-95944680-e213-11ea-8611-22ae2595f1d5.png)

On this screenshot, the **Blocs CMS** field (`contentbuildersMain`) is a Neo field and the **Blocs CMS - Hero** field (`blockHero`) is a Supertable field in one of the Neo field's blocktypes. Both cogwheel links points to the settings of the **Blocs CMS** field : `/admin/settings/fields/edit/13`.

**Expected behavior:**
  - the cogwheel link of the **Blocs CMS** field (`contentbuildersMain`) should point to the settings of the Neo field (in my case `/admin/settings/fields/edit/13`)
  - the cogwheel link of the **Blocs CMS - Hero** field (`blockHero`) should point to the settings of the corresponding Neo "subfield" (in my case `admin/settings/fields/edit/15`)

**Comment by mmikkel** [comment]
Yeah, that's expected. I intentionally didn't design CPFI to support anything other than native fieldtypes. The only native nested fieldtype is Matrix, where it isn't possible to link to sub fields' settings - so any sub field handles CPFI attaches itself to, will link to the root/global/parent field.

I'm not sure how Neo works (never used it), but based on the settings URL for your Hero field I'm assuming Neo sub fields are actually normal/global fields. I'll look into if there's maybe a way to add the cogwheels in a different way that will work for any global field regardless of them being nested inside another field or not. But, if that isn't possible I'm not going to add anything to support Neo specifically.

**Comment by mmikkel** [comment]
By the way – I assume that another thing that probably won't work with Neo, is that there won't be cogwheels in any new blocks you create, until after the entry has been saved and the page has reloaded.

**Comment by lhs-dev** [comment]
I just downgraded CPFI to 1.1.3 and it does work as expected with Neo field and their subfields; and the cogwheel even shows up for newly created blocks, event before saving and relaoding.

And you're right, Neo subfield are created as global fields (as opposed to Matrix subfields), and they do have their own URL.

**Comment by mmikkel** [comment]
If CPFI used to work properly with Neo, that’s either purely coincidental or because the Neo itself contains code to actively support CPFI (I see it’s listed here: https://github.com/spicywebau/craft-neo/blob/master/docs/plugin-compatibility.md#plugin-compatibility)

That said - I’ll look into it, but I want to keep complexity at a minimum so adding logic to support specific third party field types is not something I’m going to do.

**Comment by lhs-dev** [comment]
I completely understand that you don't want to complexify your code to support third-party plugins.
Thanks for taking the time to look into it anyway!

**Comment by mmikkel** [comment]
Resolved in [CP Field Inspect v. 1.2.2](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.2.2)
