### ISSUE TITLE
Cogwheel doesn't show anymore after updating to Craft 3.6.0

### ISSUE THREAD

**Issue by frontedbe** [mmikkel/CpFieldInspect-Craft#19]
Hi!

I've just updated to Craft 3.6.0 and the cog wheel doesn't appear anymore. 
The "Show field handles in edit forms" and allowAdminChanges are definitely set to true.

Thanks!

**Comment by mmikkel** [comment]
Thanks for reporting that @mdominguez – dammit, I swear it was still working with the RC 🤔  Oh well, I'll get a fix out ASAP.

**Comment by mmikkel** [comment]
Should be resolved in [CP Field Inspect v. 1.2.4](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.2.4)!

**Comment by frontedbe** [comment]
Awesome, thanks for the quick fix @mmikkel!
