### ISSUE TITLE
Cog Not Visible

### ISSUE THREAD

**Issue by brandondeweese** [mmikkel/CpFieldInspect-Craft#2]
Hi,

This plugin is one of my favorites, but for some reason, I can't see the cogs on my latest install. I'm the only user and admin. All plugins and Craft are up to date. I've signed out and back in. No dice. Any clue as to why this would be happening?

**Comment by mmikkel** [comment]
Hi @brandondeweese, just testet CP Field Inspect on a clean install of Craft 3.0.14, and the cogs are displaying for me.

– Do you see any JavaScript errors in your browser's dev tools (console)?
– Which browser and OS are you using?
– What other plugins do you have installed?
