### ISSUE TITLE
When returning from editing field, opened tab is not respected

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/CpFieldInspect-Craft#20]
Steps to reproduce:

1 Open entry edit page with multiple tabs
2 Open some tab that is not first one
3 Click on gear icon to go to field settings
4 Save field
5 User is returned to entry edit page, but firs tab is opened, not one that was opened before

**Comment by mmikkel** [comment]
Right, this has been bothering me for a while. Should be resolved in [CP Field Inspect 1.2.5](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.2.5).
