### ISSUE TITLE
Plugin seams to be broken in 3.7.28

### ISSUE THREAD

**Issue by KarelJanVanHaute** [mmikkel/CpFieldInspect-Craft#21]
Hey 

The plugin stopped working in a 3.7 version. Not sure which. Just tested it in a clean installation of 3.7.28. And the plugin doesn't work anymore.

**Comment by mmikkel** [comment]
Hm, it's working fine on 3.7.28 on my end.

Can you confirm that the following are all true in your current environment:

- The logged-in user is an admin
- The "Show field handles in edit forms" admin user preference is enabled
- `allowAdminChanges` is true

If yes, are you getting any JavaScript errors? Do you have any other plugins or custom modules installed?

**Comment by KarelJanVanHaute** [comment]
Mmmm strange things are happening. Now it's working indeed. Must be a conflict with another plugin or some custom code. 
Digging deeper. 
Sorry for the interruption.

**Comment by mmikkel** [comment]
No problem :)

Maybe you're running into [this](https://github.com/craftcms/cms/issues/2473). If that's the case, look [here](https://github.com/mmikkel/CpFieldInspect-Craft#still-nothing) for the fix.
