### ISSUE TITLE
Feature Request: add "Edit Field Layout" to edit entry pages

### ISSUE THREAD

**Issue by jrrdnx** [mmikkel/CpFieldInspect-Craft#22]
Good afternoon and fantastic plugin!

Similar to how Globals have an "Edit Global Set" button link at the bottom of the global set, would it be possible to have an "Edit Field Layout" button at the bottom of entry edit pages?

Thanks!

**Comment by mmikkel** [comment]
Thanks @jrrdnx!

Entry edit pages already have a button like that – it's just located in a slightly different spot:

![CleanShot 2022-03-28 at 20 50 58@2x](https://user-images.githubusercontent.com/298510/160466634-1d21864d-6674-424d-b4cc-986a17f5664a.png)

**Comment by jrrdnx** [comment]
Oops, completely missed that. Thanks!
