### ISSUE TITLE
Seems to break purchasing from plugin store

### ISSUE THREAD

**Issue by urgentdotagency** [mmikkel/CpFieldInspect-Craft#25]
Hi,
Running version 1.4.1 with Craft 3.7.38 seems to break any way to purchase plugins from the plugin store for me, on several different sites.
I can install free plugins and trials, but the Buy button or Add to cart buttons simply do nothing.
Trying to add to cart from the "Active trials" section of an opened cart give a "Couldn’t add all items to the cart" or "Couldn't item to cart" error, but no console errors or anything.
Only error that pointed me to this plugin was trying to purchase one trial via Settings>Plugins>[Trial plugin]->Buy Now, which goes "plugin-store/buy/[plugin]/standard" and throws a "Uncaught (in promise) URIError: malformed URI sequence" error in the console.

**Comment by mmikkel** [comment]
Thanks for reporting that, @urgentdotagency. I'll have a fix out ASAP.

**Comment by mmikkel** [comment]
Should be resolved in [CP Field Inspect v. 1.4.2](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.4.2) – thanks again for reporting!
