### ISSUE TITLE
[BUG] Clicking the cog throws a 404 on multilanguage site

### ISSUE THREAD

**Issue by Antimated** [mmikkel/CpFieldInspect-Craft#26]
**Issue:**
Clicking the cog next to a handle of a field or the field within a matrix gives me a 404.
When clicking I get the following url structure:
- http://site.test/craft/settings/fields/edit?site=defaultNl/1

If I append the `site` query param to the end of the url I get the desired page (not sure why the specific site is relevant tho):
- http://site.test/craft/settings/fields/edit/1?site=defaultNl <-- this works

![Screenshot 2022-05-05 at 11 43 23](https://user-images.githubusercontent.com/2869409/166900194-eaa8de75-6a85-4d84-b2e4-9b7bc883a290.png)

**Extra info**
- Multi language: Yes
- Craft pro version: No

**Plugins**
- Craft: 4.0.0.1
- CP field inspect: 1.4.2
- Additional plugins can be provided if needed

**Comment by mmikkel** [comment]
Thanks for reporting that. Should be resolved in [v. 1.4.3](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.4.3)!
