### ISSUE TITLE
Button placement

### ISSUE THREAD

**Issue by wmdhosting** [mmikkel/CpFieldInspect-Craft#29]
Hey, Great plugin :)

Any chance to place **Category edit** on same place as Entry type.. 
as its get pushed by other plugins..

![Snag_11d465e6](https://user-images.githubusercontent.com/76176291/171012349-dd0905fb-0ccb-49d4-a5de-0e8b827d2580.png)

**Comment by mmikkel** [comment]
Not really something I can fix. Field Inspect uses a template hook to render that button, and Craft 3 doesn’t have a hook to render the button in that location, for categories. It’s also not possible for Field Inspect to affect the order of other plugins’ output.

FWIW, on Craft 4 the button does render in the same spot for categories and entries, thanks to the unified element editor in 4.0.
