### ISSUE TITLE
Add support for built in fields

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/CpFieldInspect-Craft#3]
For example, fields of user model, or built in title and post date for entries.

Of course date or title would not direct to any field page (these fields are built in), buy twig variable these fields are attached to should still show up.

**Comment by mmikkel** [comment]
Hi @piotrpog, sorry for missing this issue. PRs are very welcome, but I don't think I'll add Field Inspect cogwheels for native fields anytime soon myself. I don't really see where they'd fit in the current CP design for something like the entry editing screen, and I also don't really feel they'd be necessary – there aren't too many native fields and it's easy enough to remember their handles IMO.
