### ISSUE TITLE
Craft 5 > Beta 11

### ISSUE THREAD

**Issue by wmdhosting** [mmikkel/CpFieldInspect-Craft#39]
Button gets eaten up :)

![Snag_bdc1aeb](https://github.com/mmikkel/CpFieldInspect-Craft/assets/76176291/1fc99961-4bf7-4b8a-9841-22ea61a050ca)

**Comment by mmikkel** [comment]
Hm, I'm not able to reproduce that. Are you saying the "Edit entry type" button is initially visible, then disappears after 1 second on pageload?

Do you have any other plugins or custom modules installed?

Edit: I was able to reproduce by changing the entry type, and when changing a field. Will get a fix out shortly :)

**Comment by wmdhosting** [comment]
yes...  

I tested  again. 

I see now seems something to do with Hyper 

Edit: you right.   when chanign other fields too :)

**Comment by mmikkel** [comment]
Fixed in [2.0.0-beta.4](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/2.0.0-beta.4). Thanks for reporting that @wmdhosting 👍
