### ISSUE TITLE
Cogwheel missing for categories?

### ISSUE THREAD

**Issue by frontedbe** [mmikkel/CpFieldInspect-Craft#4]
Hey there,
It's been a couple times since I've noticed the cog wheel doesn't show up when editing a category, although the README states it should. As this is nothing critical I still thought you should know :)

I'm running the latest Craft (3.0.25) and CP Field Inspect (1.0.4)
[View screenshot](https://cl.ly/d0509930a949)

**Comment by mmikkel** [comment]
Hi @mdominguez – thanks for contributing! I'll take a look at it ASAP.

**Comment by mmikkel** [comment]
Hi @mdominguez – I just released [CP Field Inspect v. 1.0.5](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.0.5), which should fix this issue.
