### ISSUE TITLE
Add links to entry types settings in matrix fields blocks

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/CpFieldInspect-Craft#40]
I have found that in craft 5 i often need to visit entry type settings pages when working on matrix fields.
Could you perhaps add links to matrix field blocks which would link to entry type of the specific block?

**Comment by mmikkel** [comment]
CP Field Inspect adds links to Matrix entries' entry type settings to the nested entries' action menus (i.e. the `...` disclosure menu), for the "Cards" and "As inline-editable blocks" view modes:

![CleanShot 2024-05-20 at 10 43 19@2x](https://github.com/mmikkel/CpFieldInspect-Craft/assets/298510/5fffa424-0c4a-4b07-82cf-b902c04706ea)
