### ISSUE TITLE
Links to fields disappear after switching entry type

### ISSUE THREAD

**Issue by piotrpog** [mmikkel/CpFieldInspect-Craft#5]
When user switches entry type for entry, cogwheel links disappear.

**Comment by mmikkel** [comment]
Hi @piotrpog – thanks for contributing. I haven't actually noticed that, it might be something new. Which Craft version are you seeing this behaviour on?

**Comment by piotrpog** [comment]
Error occurs on clear install, without any other plugins. This is my system info:

PHP version 	7.2.2
Database driver & version 	MySQL 5.5.5
Image driver & version 	GD 7.2.2
Craft edition & version 	Craft Solo 3.0.25
Yii version 	2.0.15.1
Twig version 	2.5.0
Guzzle version 	6.3.3
Imagine version 	0.7-dev

**Comment by mmikkel** [comment]
Sweet, thanks for the extra info @piotrpog. I'm able to reproduce the issue; will try to get this sorted ASAP.

**Comment by mmikkel** [comment]
Hi @piotrpog – I just released [CP Field Inspect v. 1.0.5](https://github.com/mmikkel/CpFieldInspect-Craft/releases/tag/1.0.5), which should fix this issue.
