### ISSUE TITLE
When clicking Matrix block header bar, screen jumps upwards

### ISSUE THREAD

**Issue by lindseydiloreto** [mmikkel/CpFieldInspect-Craft#9]
Very weird behavior which seems to be part of Craft itself, but made _significantly worse_ when using CP Field Inspect...

Clicking on the header of a Matrix block sometimes (not always) makes the page jump up a little bit. When CP Field Inspect is installed, the page jumps up _much more frequently_ and moves _a lot farther_.

No idea why this might be happening! Any thoughts?

**Comment by lindseydiloreto** [comment]
Link to Slack discussion... (where I already tagged you, sorry)

https://craftcms.slack.com/archives/C02M5G76W/p1548976425231000

These observations seem relevant...

>Looks like something in the MatrixInput.js

>Seems to actually be correlated with ticking the checkbox to the left of each Matrix block title rather than expand/collapsing the block

If this issue is more of a Craft problem than a CP Field Inspect problem, we'll kick it over to P&T. 👍

**Comment by mmikkel** [comment]
Having trouble reproducing this – I've never noticed it before, but in double-clicking a bunch of times to expand/collapse I do see a very minor scroll/jump; like it's focusing something on the page? Doesn't happen a whole lot, and I'm not seeing any difference whatsoever in this behaviour with Field Inspect enabled or disabled, though.

What browser are you using?

**Comment by turnstylerj** [comment]
I can reproduce this in Chrome on macOS, and it seems to be correlated to ticking the select box on the top left of each Matrix block. If I tick the select box of a Matrix block further down the page, the block jumps to the top of the window.

**Comment by mmikkel** [comment]
@turnstylerj Yeah, ticking the check box on a block close to the bottom of the viewport does make stuff jump for me, too. This might be intended behaviour (I haven't looked at the relevant JS source code in Craft). It's probably related to the original issue, too – I don't get why the checkbox is checked/unchecked when you double-click the bar to expand/collapse. Feels like a bug.

Testing with and without Field Inspect enabled, I'm still not seeing a difference in behaviour, though – so I'm not convinced the plugin actually plays a role in this :)

**Comment by turnstylerj** [comment]
Agreed, I don't think clicking the bar should select the checkbox. I want to double tap to toggle collapse state far more often than I need to multi-select blocks.

**Comment by lindseydiloreto** [comment]
@mmikkel Thanks for looking into this! Yeah, it's hard to say how much CP Field Inspect is contributing... but it seems clear that the root cause is somewhere in Craft core.

I've filed an issue with Craft directly:

https://github.com/craftcms/cms/issues/3762

We'll move any further discussion over to that thread. Thanks again! 🍺
